require('dotenv').config();
const { ApolloServer } = require('apollo-server-express');
const express = require('express');
const { Neo4jGraphQL } = require('@neo4j/graphql');
const neo4j = require("neo4j-driver");

const typeDefs = require('./schema/graphql-schema');
const app = express();


// connect to neo4J db
const driver = neo4j.driver(
  process.env.NEO4J_URI || "bolt://localhost:7687",
  neo4j.auth.basic(process.env.NEO4J_USER || 'neo4j', process.env.NEO4J_PASSWORD || 'Reyeswright5')
);


/*
 * Creates an executable GraphQL schema object from GraphQL type definitions
 * including autogenerated queries & mutations.
 */

const neoSchema = new Neo4jGraphQL({ typeDefs, driver })

/*
 * Creates a new ApolloServer instance, serving the GraphQL schema
 * created using Neo4JGraphQL library from above and injecting the Neo4j driver
 * instance into the context object so it is available in the
 * generated resolvers to connect to the database.
 */
const server = new ApolloServer({
  context: {
    driver,
    driverConfig: { database: process.env.NEO4J_DATABASE },
  },
  schema: neoSchema.schema,
  introspection: true,
  playground: true,
})

// Specify HOST, PORT and PATH for GraphQL endpoint
const PORT = process.env.GRAPHQL_SERVER_PORT || 4001
const PATH = process.env.GRAPHQL_SERVER_PATH || '/graphql'
const HOST = process.env.GRAPHQL_SERVER_HOST || '0.0.0.0'

/*
 * Apply Express middleware for authentication, etc
 * This also also allows us to specify a PATH for the GraphQL endpoint
 */

server.applyMiddleware({ app, PATH })
app.listen(PORT, () => {
  console.log(`GraphQL server is up & away at 🚀 http://localhost:${PORT}/graphql`)
})
